### ISSUE TITLE
Cannot run preprocessing. NameError: name 'calculate_protein_embeddings' is not defined

### ISSUE THREAD

**Issue by Yang-Wang-2020** [AlexanderKroll/ProSmith#2]
Calculating protein embeddings:
Traceback (most recent call last):
  File "code/preprocessing/preprocessing.py", line 58, in <module>
    calculate_protein_embeddings(all_sequences, args.outpath, args.prot_emb_no)
NameError: name 'calculate_protein_embeddings' is not defined

Could you take a look?

Thanks,
Yang

**Comment by fmoorhof** [comment]
Also having big reproducibility issues right now. This might help you for the first steps:
You need to make the package installable that local imports are recognized. You can do this by writing a `setup.py`  file with this minimal content:

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ {.python .numberlines}
from setuptools import setup, find_packages

setup(
    name="prosmith",
    description="Prosmith",
    package_dir={'': 'code'},
    packages=find_packages(where='code'),
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
then you can install the project with `pip install .` 
make sure you create the `setup.py` where readme.md is and call `pip install .` from there...

**Comment by Yang-Wang-2020** [comment]
Thanks for your reply. 
I solved this by uncommenting the "#from protein_embeddings import *" from the preprecessing.py

A few more things could be helpful.
1. protein_embedding.py has some unwanted indent that caused error.
2. Some packages are missing in the readme. e.g esm. Could you release a requirements.txt or a poetry.lock file for user to install all the required packages?

Thank you,
Yang

**Comment by fmoorhof** [comment]
I had all the mentioned issues as well but was too hesitated to open a PR, too:/

**Comment by AlexanderKroll** [comment]
Sorry for my late response, I was very busy during the last weeks. 
@fmoorhof thanks for fixing the issues! I merged your pull request.

**Comment by Yang-Wang-2020** [comment]
Thank you Both!
