### ISSUE TITLE
Missing transformer model weights

### ISSUE THREAD

**Issue by maxall41** [AlexanderKroll/ProSmith#4]
It seems like the transformer model trained for ESP prediction is not included in the repo or in the Zenodo folder. I can only find the pretrained KM prediction model and the BindingDB model. Could you upload the trained ESP transformer model (`ESP_1gpus_bs24_1e-05_layers6.txt.pkl`)?

Thanks,
Max

**Comment by AlexanderKroll** [comment]
Dear Max,

I uploaded the missing model weights "ESP_2gpus_bs48_1e-05_layers6.txt.pkl". I also generated a new GitHub repository, which should make it much easier to use the already trained ProSmith model for the enzyme-substrate prediction task: https://github.com/AlexanderKroll/ESP_ProSmith
