### ISSUE TITLE
chemBERT embedding question

### ISSUE THREAD

**Issue by GrantMcConachie** [AlexanderKroll/ProSmith#7]
Hello,

When you are generating smiles embeddings of chemBERT and use `smiles_bert = AutoModelForMaskedLM.from_pretrained(SMILES_BERT)` in the `smiles_embeddings.py` there is a randomly initialized projection head that huggingface adds to the model. I have two questions:

1) Do you think it could be a problem that the embeddings from chemBERT are random every time the model is initialized?

2) why you don't use a pipeline (https://huggingface.co/docs/transformers/en/main_classes/pipelines) with the feature-extraction task to generate the embeddings?

Thanks,

Grant

**Comment by AlexanderKroll** [comment]
Hi Grant,

sorry for my late response.

1. As far as I understand, those are just the parameters for regression prediction tasks, right? Hence, I think this shouldn't affect the embedding generation process.

2. I wasn't aware of huggingface pipelines. I will look into it, thanks :)
