### ISSUE TITLE
code training_GB encountered an IndexError error

### ISSUE THREAD

**Issue by luohuiqian** [AlexanderKroll/ProSmith#8]
Hello, when I run your code training_GB in your ESP dataset, I encounter an index error: IndexError: Resulting IndexError in DataLoader worker process 0
Original Traceback (most recent call last):

File "/mnt/usb/code/luohuiqian/prosmith/code/training/utils/datautils.py",  line 112, in __getitem__
raise IndexError(f"Index {idx} out of bounds for dataset with length {len(self.mappings)}")
IndexError: Index -889 out of bounds for dataset with length 967

May I ask where I didn't handle it properly, which caused this problem to occur? Do you have any clues

**Comment by AlexanderKroll** [comment]
Hi luohuiqian, 

sorry for my late response. It is hard to tell what is going on without further information. Your index seems to be negative, which is weird. Did you change anything from the code provided in the repository?
